version: '3.7'

services:
  web:
    container_name: techscenar
    restart: always
    build:
      context: .
      dockerfile: dockerfile.tech
    ports:
      - "0.0.0.0:8000:8000"
    command: bash -c "python techscenar/manage.py collectstatic --noinput && python techscenar/manage.py runserver 0.0.0.0:8000"