FROM python:3.12

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .
COPY languages/ctt/templates/ templates/

CMD ["python3", "-m" , "flask", "run", "--host=0.0.0.0"]