FROM python:3.11

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .
COPY languages/ctt/templates/ templates/

EXPOSE 5000

CMD ["python3", "app.py"]