FROM python:3-buster

ARG ICS_URL

EXPOSE 8000

WORKDIR /

COPY . .

RUN rm -rf /techscenar/staticfiles

RUN export ICS_URL=${ICS_URL}

RUN pip3 install --upgrade pip

RUN pip3 install -r requirments.txt

# CMD ["python", "./techscenar/manage.py", "runserver", "0.0.0.0:8000"]
