FROM python:3-buster

EXPOSE 8000

WORKDIR /

COPY . .

RUN rm -rf /techscenar/staticfiles

RUN pip3 install --upgrade pip --root-user-action=ignore

RUN pip3 install -r requirments.txt --root-user-action=ignore
